### ISSUE TITLE
Mixpanel instance still in memory and sending requests when app becomes active

### ISSUE THREAD

**Issue by NickyWeber** [mixpanel/mixpanel-iphone#285] opened 2015-07-10 15:18 UTC
iOS Version 8.3
Mixpanel verison 2.8.1

It seems as if you create an instance of Mixpanel with the `initWithToken...` method it will remain in memory still listening to events like `UIApplicationDidBecomeActiveNotification`. 

A breakpoint in `Mixpanel.m -applicationDidBecomeActive` should suffice to see the behaviour.

Some steps to reproduce:
* Create an instance of Mixpanel with initWithToken method
* Store that instance in a property with strong attribute
* set that property to nil
* Send app to background
* Add breakpoint in `Mixpanel.m -applicationDidBecomeActive`
* Open app again 

When setting
```
#define DISABLE_MIXPANEL_AB_DESIGNER
```

This bug does not occur.

**Comment by samgreen** [comment] 2015-07-10 18:14
Thanks so much for this detailed report. Very clear instructions. I will investigate and get back to you today.

**Comment by samgreen** [comment] 2015-07-10 19:17
@NickyWeber I was able to reproduce this issue. Looking at a fix now.

**Comment by NickyWeber** [comment] 2015-07-10 20:41
@samgreen Wow, that was fast, thank you very much.

**Comment by samgreen** [comment] 2015-07-14 23:04
@NickyWeber So it occurs to me that this issue will not be easily resolved with the existing API. Since we create an internal instance for use as a singleton. We have an internal static variable that will stick around for the life of the application to allow easy access to Mixpanel once initialized.

Can you tell me a bit more on a higher level, about what you're trying to accomplish and how this instance sticking around in memory is preventing that?

**Comment by NickyWeber** [comment] 2015-07-15 09:35
We have implemented an opt out switch for the user. As soon as the user opts out any tracking has to be disabled. A nice property that will disable any kind of requests or a dedicated method to tell the tracker that a user opted out would do.

**Comment by samgreen** [comment] 2015-07-15 23:10
Do the work arounds mentioned by #277 help at all?

**Comment by NickyWeber** [comment] 2015-07-16 10:45
It doesn't. Disabling tracking in general has already been achieved except this one case. Can you provide a way to get rid of the singleton?

**Comment by samgreen** [comment] 2015-07-16 19:33
@NickyWeber How about we add a global method, something like `[Mixpanel setDisabled:YES]`, then if you attempt to log an event, we'll just warn to the console that Mixpanel has been explicitly disabled.

**Comment by NickyWeber** [comment] 2015-07-22 19:14
@samgreen That is a good solution. However I'd rather not have the tracker clutter the console for every event in general. Maybe just for a logging level of verbose?

**Closed** 2016-02-17 00:26 UTC
