### ISSUE TITLE
killed by: active assertions beyond permitted time: [Mixpanel applicationDidEnterBackground:]

### ISSUE THREAD

**Issue by leeliu** [mixpanel/mixpanel-iphone#95] opened 2013-12-20 13:09 UTC
I'm getting this in my console after backgrounding my app:

    Dec 20 04:51:52 Lees-iPhone-5s backboardd[31] <Warning>: abiosapp[1101] has active assertions beyond permitted time: 
        {(
            <BKProcessAssertion: 0x170277f00> identifier: Called by abiosapp, from -[Mixpanel applicationDidEnterBackground:] process: abiosapp[1101] permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:1101 preventSuspend  preventIdleSleep  preventSuspendOnSleep 
        )}
    Dec 20 04:51:52 Lees-iPhone-5s backboardd[31] <Warning>: Forcing crash report of abiosapp[1101]...
    Dec 20 04:51:53 Lees-iPhone-5s backboardd[31] <Warning>: Finished crash reporting.

The last item for my app exactly 3 minutes before this was the call to mixpanel /engage api.

**Comment by samgreen** [comment] 2015-07-09 23:09
@johnryan @leeliu I'm unable to reproduce this issue, are you still experiencing this? Once I'm able to reproduce this I'm sure that it will be a quick fix.

**Comment by ajstiles** [comment] 2015-07-14 03:53
We are seeing this consistently right now. What info can I get you to help?

**Comment by samgreen** [comment] 2015-07-14 19:28
Can you slim down your project to the smallest amount of code that reproduces the issue?

**Comment by samgreen** [comment] 2015-07-18 01:26
Closing this issue, since we can't repro on our end and we don't have a sample project. Please open another issue if you're able to help us track this down.

**Closed by samgreen** 2015-07-18 01:26 UTC
Labels: bug

**Comment by A2K** [comment] 2015-08-20 23:27
I have a crash log from a user which seems to be caused by the same problem:

```
Application Specific Information:
<BKNewProcess: 0x157fa64d0; com.ambrella.rain; pid: 18964; hostpid: -1> has active assertions beyond permitted time: 
{(
    <BKProcessAssertion: 0x159027760> id: 18964-CF0EE6FF-DA34-46D3-8AA8-4589A08B3ACB name: Called by Mixpanel, from -[Mixpanel applicationDidEnterBackground:] process: <BKNewProcess: 0x157fa64d0; com.ambrella.rain; pid: 18964; hostpid: -1> permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:18964 preventSuspend  preventIdleSleep  preventSuspendOnSleep 
)}
```

I could not reproduce it either, should I report if I receive more crash reports like this?

**Comment by ryanseams** [comment] 2015-11-11 19:14
I wanted to add some additional context here, and see if we can add some information which can assist in resolving this issue.

To reproduce this, you will need to:
1. Open and close the app quickly a few times
2. Be using interstitials (specifically OtherLevels in this case, this is not a confirmed step but would be nice to know if the other users with this issue use these as well or not)

This issue seems to be isolated to the fact there is a variable called taskId with the library. When the application enters the background as detailed [here](https://github.com/mixpanel/mixpanel-iphone/blob/5a8bde0fc70da05c5054e11986c9aaf6d38fa5af/Mixpanel/Mixpanel.m#L1132-L1156), there is the potential for the taskId to be overwritten when the app is opened and closed quickly since it is dispatched to be processed on a serial queue in the background.

This information was provided by a customer.

Please see the full crash log below:
```
assertiond[64] <Warning>: <BKNewProcess: 0x1465b0dc0; com.***.general; pid: 61936; hostpid: -1> has active assertions beyond permitted time: 
{( 
<BKProcessAssertion: 0x14670b080> id: [long GUID was here] name: Called by ***, from -[Mixpanel applicationDidEnterBackground:] process: <BKNewProcess: 0x1465b0dc0; com.***.general; pid: 61936; hostpid: -1> permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:61936 preventSuspend preventIdleSleep preventSuspendOnSleep , 
<BKProcessAssertion: 0x14660e530> id: [long GUID was here] name: Called by ***, from __40-[OLLocation geoFeedAPIWithToken:retry:]_block_invoke process: <BKNewProcess: 0x1465b0dc0; com.***.general; pid: 61936; hostpid: -1> permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:61936 preventSuspend preventIdleSleep preventSuspendOnSleep , 
<BKProcessAssertion: 0x14781a210> id: [long GUID was here] name: Called by ***, from __40-[OLLocation geoFeedAPIWithToken:retry:]_block_invoke process: <BKNewProcess: 0x1465b0dc0; com.***.general; pid: 61936; hostpid: -1> permittedBackgroundDuration: 180.000000 reason: finishTask owner pid:61936 preventSuspend preventIdleSleep preventSuspendOnSleep 
)}
```

**Comment by patedit** [comment] 2015-12-16 23:36
This should be solved in the last release
