### ISSUE TITLE
UIControlEventTouchDown issues

### ISSUE THREAD

**Issue by umbri** [mixpanel/mixpanel-iphone#588] opened 2016-10-14 16:32 UTC
**Integration Method:** Manual
**Xcode Version:** 8A218a
**Library Version:** 3.0.4
**Platform:** iOS
**Device:** iPhone 6s
**Language:** Objective-C
**Description:** 
Mixpanel is causing issues with UIControlEvents, here is library that I use, and before mixpanel integration work as expected, after UIControlEventTouchDown don't fire [code](https://github.com/LeoNatan/LNPopupController/blob/058e06664f12438c5faa874ebaa5c834df24dc79/LNPopupController/LNPopupController/Private/LNPopupCloseButton.m#L43)

**Expected Behavior:** I think problem is in your swizzling code

**Comment by yarneo** [comment] 2016-10-18 04:10
Hey @umbri thanks for reaching out. The swizzling isn't supposed to override implementation but rather add on to it. I doubt it is connected, but would love to try and reproduce this and see what went wrong. Would you be able to send to support@mixpanel.com this issue so we can get more information about your project and we can take a deeper dive and see what's the cause?

Thank you!

**Comment by umbri** [comment] 2016-10-18 09:57
Sorry, about few details, it was on starting weekend :)
I figured whats going wrong, the problem is with: `UILongPressGestureRecognizer`

Here in [https://github.com/mixpanel/mixpanel-iphone/blob/master/Mixpanel/Mixpanel.m#L930](Mixpanel.m) 
And here [https://github.com/LeoNatan/LNPopupController/blob/master/LNPopupController/LNPopupController/Private/LNPopupController.m#L761](LNPopupController.m)

**Comment by yarneo** [comment] 2016-10-18 16:47
Thanks @umbri :)
We have exposed a variable that should disable the gestureRecognizer. If you set: enableVisualABTestAndCodeless to NO, that should fix your problem!

**Comment by umbri** [comment] 2016-10-19 19:25
Hi,
Today I checked your proposal and I can confirm that setting:
`[[Mixpanel sharedInstance] setEnableVisualABTestAndCodeless:NO]`
does not solve my problem

**Comment by pchien** [comment] 2016-10-19 23:45
Hi @umbri. I did a bit of investigation around `setEnableVisualABTestAndCodeless:`. Because `testDesignerGestureRecognizer` in `Mixpanel.m` is created on a `dispatch_async` call, you need to make sure to call `setEnableVisualABTestAndCodeless:NO` at least one run loop after you initialize `Mixpanel sharedInstance`. When calling it immediately, `testDesignerGestureRecognizer` didn't exist yet for me, but when I called it in a `dispatch_async` call (on `dispatch_get_main_queue()`) as well, then the gesture recognizer existed and it was disabled correctly. Hope this helps!

**Comment by pchien** [comment] 2016-10-20 00:33
@umbri the need for calling one run loop later has been removed in https://github.com/mixpanel/mixpanel-iphone/pull/590 (which was just merged) so whenever you call `setEnableVisualABTestAndCodeless:NO` it should work.
In case you'd rather pull from master than jump through `dispatch_async` hoops.

**Closed** 2016-10-20 00:34 UTC
