### ISSUE TITLE
Crash in mixpanel-iphone v3.3.3

### ISSUE THREAD

**Issue by ApoorvKhatreja** [mixpanel/mixpanel-iphone#795] opened 2018-09-19 15:34 UTC
**Integration Method:** CocoaPods
**Xcode Version:** 10.0
**Library Version:** 3.3.3
**Platform:** iOS
**Language:** Swift & Objective-C mixed
**Description:** We're seeing this crash for some iOS 9 & iOS 12 users, seems to be related to the `identify:usePeople:` method call.
**Expected Behavior:** 
The SDK shouldn't crash.

![screen shot 2018-09-19 at 11 31 18](https://user-images.githubusercontent.com/143720/45764111-f2d68600-bbff-11e8-9d76-13cbd00f8c71.png)

**Comment by ApoorvKhatreja** [comment] 2018-09-19 15:35
A more detailed stack trace, if it is helpful:

![screen shot 2018-09-19 at 11 35 16](https://user-images.githubusercontent.com/143720/45764185-26b1ab80-bc00-11e8-8312-0447fe93864f.png)

**Comment by zihejia** [comment] 2018-10-11 03:46
hi @ApoorvKhatreja , sorry for the late response. Does this crash happen consistently or a one off thing?

**Comment by zihejia** [comment] 2018-10-15 20:43
Hi @ApoorvKhatreja , have you by any chance called `- (void)archive` explicitly? or Could you give us more information regarding how this could happen if you can? We have not received any similar crashes so eager to solve this if possible.

**Comment by ApoorvKhatreja** [comment] 2018-10-15 20:53
@zihejia This crash does not happen consistently, in fact I'm not able to personally reproduce it. I've noticed it on Crashlytics, and seems like this crash happens with some frequency. I have no record of calling the `archive` method explicitly anywhere in my app, however I do use the People API and use the `identify:usePeople:` method for that.

**Comment by zihejia** [comment] 2018-10-15 21:20
Hi @ApoorvKhatreja , thanks for the info, what is the frequency of this crash?

**Comment by zihejia** [comment] 2018-10-15 22:01
Hi @ApoorvKhatreja , sorry about the pain, we will continue to investigate. In the meantime, in case you didn't know, we also have a swift library which has reached full parity which we recommend for swift projects. https://github.com/mixpanel/mixpanel-swift

**Comment by ApoorvKhatreja** [comment] 2018-10-16 01:56
@zihejia Thanks for the update! Would you recommend switching to the Swift version even for Obj C-Swift mixed projects?

**Comment by zihejia** [comment] 2018-10-16 04:54
Hi @ApoorvKhatreja , Swift version is recommended for swift project. It's fine for using Obj C if you are Obj C - Swift mixed.

**Comment by zihejia** [comment] 2018-10-23 18:38
Hi @MayeuldP , could you also help to share the crash log? We will have a look at this issue this week.

**Comment by zihejia** [comment] 2018-10-24 04:36
Hi @ApoorvKhatreja @MayeuldP , we have found the root cause of this issue, there could be threads trying to modify events at the same time while events archive is happening.  We have released v3.3.6 and has a fix for this issue https://github.com/mixpanel/mixpanel-iphone/releases/tag/v3.3.6.

Again, thanks so much for raising it! Closing this one now, please feel free to reopen it if the problem still exists.

**Closed by zihejia** 2018-10-24 04:36 UTC

**Comment by ApoorvKhatreja** [comment] 2018-10-24 14:29
@zihejia Thanks for the update!
