### ISSUE TITLE
Mixpanel `archive` thread safe?

### ISSUE THREAD

**Issue by bejar37** [mixpanel/mixpanel-iphone#338] opened 2015-09-04 20:31 UTC
Hi,
I've noticed that on occasion, my users are losing their super properties. 
After doing some investigation, I realized that on app crashes, or even sometimes when terminated from the background, the super properties will not be archived and thus lost.

I'm looking into using the `archive` method to save my properties after important events occur, but I realized that the library exclusively archives from a private serial queue. Thus I'm afraid that I could cause data corruption by calling `archive` from the main thread or my own serial queue. 

Is this a latent bug?

Thanks!

**Comment by dgatwood** [comment] 2015-10-23 16:32
Don't know, but the reason for the data loss is probably related to the crash we're seeing approximately once per user, for about 4% of our user base, where archiving from the queue crashes because of the underlying data structures getting mutated during archiving.

**Comment by dgatwood** [comment] 2015-10-23 16:52
After glancing at it, no, it would not be safe to call it outside the serial queue.

Never mind about the crash.  Turns out it is caused by some patches on our side.

**Comment by dgatwood** [comment] 2015-10-23 17:17
Scratch the never mind.  There's a subtle bug here, which is that all of the methods perform a shallow copy when registering superproperties and similar tasks.  If you pass anything mutable inside one of those outer containers, you now have mutable objects that (depending on the calling code) can get mutated while Mixpanel is archiving them.

The only way I know of to (mostly) fix this reliably is to use CFPropertyListCreateDeepCopy in those methods instead of copy, while still running on the original calling thread, so that the data structures inside Mixpanel are strictly under its control.  Of course, it is still possible for a programmer doing something really silly to cause that to fail by mutating it while you're copying it, but that would clearly be a multithreading bug in the calling app.  :-)

**Comment by peymano** [comment] 2016-04-22 01:46
Possibly related: https://github.com/mixpanel/mixpanel-iphone/issues/478

**Comment by yarneo** [comment] 2016-09-01 23:13
Issue is fixed in new release! Thanks for your patience

**Closed by yarneo** 2016-09-01 23:13 UTC
Labels: bug
