### ISSUE TITLE
Mixpanel surveys doesn't react well to rotation

### ISSUE THREAD

**Issue by fatuhoku** [mixpanel/mixpanel-iphone#208] opened 2015-01-06 14:41 UTC
Portrait:

![ios simulator screen shot 6 jan 2015 14 42 12](https://cloud.githubusercontent.com/assets/430233/5630068/3928843c-95b2-11e4-9df8-8d931f9a206b.png)

Landscape:
![ios simulator screen shot 6 jan 2015 14 40 24](https://cloud.githubusercontent.com/assets/430233/5630050/1893acb0-95b2-11e4-8954-f0537d6503c7.png)

Screenie taken from iOS Simulator (iPad Air 8.1)

**Comment by malectro** [comment] 2015-01-30 23:32
thanks for pointing this out. we sadly haven't optimized surveys for ipad yet, but hopefully we'll get some design love for it in the near future.

**Comment by samgreen** [comment] 2015-07-16 21:57
This is actually functioning correctly. The intended behavior is to hide the prompt and fade it out when in landscape. This behavior is present regardless of whether the device is an iPhone or an iPad. If the keyboard is hidden, the prompt returns appropriately.

Closing this issuel.

**Closed** 2015-07-16 21:58 UTC
Labels: enhancement, surveys
