### ISSUE TITLE
Crash on archive event

### ISSUE THREAD

**Issue by johnryan** [mixpanel/mixpanel-iphone#381] opened 2015-11-12 01:24 UTC
Exception Type:  SIGSEGV
Exception Codes: SEGV_ACCERR at 0xd1606610
Crashed Thread:  9

```
Thread 9 Crashed:
0   libobjc.A.dylib                      0x33ab7ae6 objc_msgSend + 6
1   CoreFoundation                       0x22012d95 -[__NSArrayM dealloc] + 146
2   libobjc.A.dylib                      0x33ac4f8b objc_object::sidetable_release(bool) + 148
3   CoreFoundation                       0x22013db9 -[__NSDictionaryM dealloc] + 130
4   libobjc.A.dylib                      0x33ac4f8b objc_object::sidetable_release(bool) + 148
5   CoreFoundation                       0x22012d95 -[__NSArrayM dealloc] + 146
6   libobjc.A.dylib                      0x33ac4f8b objc_object::sidetable_release(bool) + 148
7   Foundation                           0x22e59509 -[NSKeyedArchiver dealloc] + 218
8   libobjc.A.dylib                      0x33ac4f8b objc_object::sidetable_release(bool) + 148
9   libobjc.A.dylib                      0x33ac53cd (anonymous namespace)::AutoreleasePoolPage::pop(void*) + 386
10  CoreFoundation                       0x2200af51 _CFAutoreleasePoolPop + 14
11  Foundation                           0x22ea5a4b +[NSKeyedArchiver archiveRootObject:toFile:] + 252
12  App                                0x002414b3 -[Mixpanel archiveEvents] (Mixpanel.m:729)
13  App                                0x0023fac1 __29-[Mixpanel track:properties:]_block_invoke (Mixpanel.m:421)
14  libdispatch.dylib                    0x341aced7 _dispatch_call_block_and_release + 8
15  libdispatch.dylib                    0x341b704f _dispatch_queue_drain + 1760
16  libdispatch.dylib                    0x341b002f _dispatch_queue_invoke + 280
17  libdispatch.dylib                    0x341b8871 _dispatch_root_queue_drain + 1570
18  libdispatch.dylib                    0x341b824b _dispatch_worker_thread3 + 92
19  libsystem_pthread.dylib              0x34341e29 _pthread_wqthread + 1022
20  libsystem_pthread.dylib              0x34341a18 start_wqthread + 6
```

**Comment by johnryan** [comment] 2015-11-12 01:26
is this a duplicate of #338 ?

**Comment by samgreen** [comment] 2015-12-23 00:21
Duplicate of #338 
 
Thanks @johnryan

**Closed by samgreen** 2015-12-23 00:21 UTC
