### ISSUE TITLE
Identity, properties and variants lost if app closed before backgrounding

### ISSUE THREAD

**Issue by gransell** [mixpanel/mixpanel-iphone#374] opened 2015-10-30 09:00 UTC
Hi

We have run into an issue with how properties and variants are archived that causes users to lose their identity, super properties and experiment variants if closing the app before backgrounding after a clean launch. I'm thinking this might also be a potential cause of #338.

Steps to reproduce:
1. Start of with an app where you have called identify and reported some super properties.
2. Background the app and close it.
3. Launch the app again. This will unarchive and remove the archived data from disk.
4. Double tap the home button and close the app without backgrounding it.
5. Launch the app again

Since the archived data is removed after unarchiving when the app is launched and never written again since it's only done when backgrounding they will be lost the next time the app is launched in step 5.

Once we launch the app again in step 5 all set: on people will result in properties sent to the unidentified queue. We also need to recalculate super properties. I'm wondering if this might also have the effect that users can switch between experiment variants since they will join experiments again and they are now an unidentified user?

I'm thinking we can work around this for now by calling flushWithCallback since that will archive. Or should we just call archiveProperties directly after calling identify or changing super properties? Not sure when we should do this for experiment variants.

**Comment by samgreen** [comment] 2016-02-17 01:03
I am unable to reproduce any data loss. Additionally, since the lifecycle of iOS applications will call `didEnterBackground:` prior to terminate, we will archive when entering the background and this will succeed.

I tested this by tracking 1000 events every 3 seconds and then force closing the app. Since you have to double tap the home button to access the app switcher and close the app, you will enter the background prior to terminating.

**Comment by kaihuppmann** [comment] 2016-02-17 13:44
Same here. I can not reproduce this one with "reality-like-usage". However when an app crashes or used in IDE with restarting the app without terminating all properties will be lost. And: Our real-life experience shows that some users do lose super properties (without crashes or IDE-usage), which somehow "proves" that there are situations in which this bug is happening. I think different handling of persistence for super and people props could fix that. Just keep the persistence file consistent during whole runtime and don't delete it when app is started and then re-write it, when app didEnterBackground.

**Comment by samgreen** [comment] 2016-02-17 18:15
Reopening issue to investigate our persistence model. Thanks for the feedback!

**Comment by kaihuppmann** [comment] 2016-02-17 20:51
Thank's

**Comment by samgreen** [comment] 2016-07-05 17:56
This was resolved with a change in v2.9.8, we no longer remove the persisted files when they load successfully.

**Closed by samgreen** 2016-07-05 17:56 UTC
Labels: bug
